compile1:
	g++ -c problema1.cpp -c -o problema1.o
	g++ problema1.o -o problema1

execute1:
	gcc -c problema1.c -c -o problema1.o
	gcc problema1.o -o problema1
	./problema1 problema1.in problema2.out
	make clean

compile2:
	g++ problema2.cpp -c -o problema2.o
	g++ problema2.o -o problema2

clean:
	rm *.o problema1 problema2
