all:
	g++ -g -std=c++17 basic2.cpp -c -o basic2.o
	g++ -g -std=c++17 basic2.o -o basic2
clean:
	find . -type f  ! -name "*.h" ! -name "*.cpp" ! -name "*.bn" ! -name "README.md" ! -name "expresii_regulate.txt" ! -name ".gitignore" ! -name "Makefile" -delete
test:
	echo "Not implemented"
test2:
	echo "Not implemented"
clean-win:
	del program.o main.o main.exe
