/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CppLibrary2 */

#ifndef _Included_CppLibrary2
#define _Included_CppLibrary2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CppLibrary2
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CppLibrary2_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
