compile1:
	g++ problema1.cpp -c -o problema1.o
	g++ problema1.o -o problema1

compile2:
	g++ problema2.cpp -c -o problema2.o
	g++ problema2.o -o problema2

compile3:
	g++ problema3.cpp -c -o problema3.o
	g++ problema3.o -o problema3

compile4:
	g++ problema4.cpp -c -o problema4.o
	g++ problema4.o -o problema4

compile-sudoku:
	g++ sudoku.cpp -c -o sudoku.o
	g++ sudoku.o -o sudoku

clean:
	rm -f *.o problema1 problema2 problema3 problema4 sudoku
