all:
	g++ -g -std=c++17 main.cpp -c -o main.o
	g++ -g -std=c++17 main.o -o main
clean:
	find . -type f ! -name "*.h" ! -name "*.cpp" ! -name "*.bn" ! -name "*.ad" ! -name "README.md" ! -name "expresii_regulate.txt" ! -name "Makefile" ! -name ".gitignore" ! -name "launch.json" ! -name "tasks.json" -delete
test:
	echo "Not implemented"
test2:
	echo "Not implemented"
clean-win:
	del program.o main.o main.exe
