FROM ubuntu:20.04
RUN apt-get -o Acquire::Max-FutureTime=86400 update
#RUN apt update
RUN apt-get install -y openjdk-11-jdk
RUN apt-get install -y python3
RUN apt-get install -y g++
RUN apt-get install -y git
