package ast;

public enum AstNodeType {
    UNDEFINED,
    PROGRAM,
    ASSIGN_STATEMENT,
    PREFIX_EXPRESSION,
    INFIX_EXPRESSION,
    IF_STATEMENT,
    LET_STATEMENT,
    BIG_NUMBER,
    BOOLEAN,
    EXPRESSION_STATEMENT,
    IDENT
}
