alphab2t = 'TYFMQXJRN AELBV  WCKS P I '
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

text = 'YEQCCQMNCKRQLTBKRTKPTEAQKRBVKNBKRQFVSBCQEVXKRQSBJVMEIBVWCKTBMQKRN'
text = 'MNCBVKNBTEERNCKRVSJRKCRNCPTICTWQTEPTICJWNQOVSCKRID'
text = 'Q VX KRQ RSLYEQ KRVS PNEKHWQHT WQKRQ NWRQT WKKR VSPN EKFTS CQKRN BQQ TW KVRQ TWKVDS MJQ KRQXT KRQ WEQCCT BMKR QVH H'
#       BLESSEDISTHEMANTHATWALKETHNOTINTHECOUNSELOFTHEUNGODLYNOPSTANDETHI
        E OF THE HUMBLE THOU WILTREARE THEIR HEART THOU WILT CAUSE THINE EAR TO HEAR TOUDGE THE FATHER LESS AND THE O

output = ''

for letter in text:
    for i, ch in enumerate(alphab2t):
        if letter == ch:
            output = output + alphabet[i]

print output